# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
  url: '%env(MAILER_URL)%'
  port: 1025
  transport: smtp
    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']
